repos:
  - repo: local
    hooks:
      - id: check-secrets
        name: Check for secrets
        entry: bash -c 'if grep -r "sk-[a-zA-Z0-9]" . --exclude-dir=.git --exclude="*.md"; then echo "❌ OpenAI API key detected!"; exit 1; fi'
        language: system
        pass_filenames: false
      - id: check-env-files
        name: Check for .env files
        entry: bash -c 'if find . -name ".env" -not -path "./.git/*" | grep -q .; then echo "❌ .env files detected! Use .env.example instead."; exit 1; fi'
        language: system
        pass_filenames: false
      - id: check-private-keys
        name: Check for private keys
        entry: bash -c 'if find . -name "*.pem" -o -name "*.key" -o -name "*_private*" | grep -q .; then echo "❌ Private key files detected!"; exit 1; fi'
        language: system
        pass_filenames: false