repos:
  # --- Hygiene: whitespace, EOF, mixed line endings, large files ---
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-ast
      - id: mixed-line-ending
        args: [--fix=auto]
      - id: check-added-large-files
        args: ["--maxkb=500"]  # block >500KB accidental blobs

  # --- Security: block obvious secrets ---
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline", "--exclude-files", "data/|attestations/"]
        exclude: '^(.*/)?(\.env(\..*)?|.*\.pem|.*\.key|.*\.crt|.*\.p12)$'

  # --- Python formatting ---
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black

  # --- Python lint (fast) ---
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format  # ruff's formatter (keeps in sync with black decisions)

  # --- Type check (incremental, quick)—skips heavy libs by config ---
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies: []
        args:
          - "--config-file=pyproject.toml"
        files: "^app/"

  # --- Optional: run fast tests on changed files only (kept lightweight) ---
  - repo: local
    hooks:
      - id: pytest-quick
        name: pytest (quick)
        entry: bash -lc 'pytest -q'
        language: system
        pass_filenames: false
        stages: [pre-push]
