import jsPDF from "jspdf";
import html2canvas from "html2canvas";

export async function lessonToPDF(element: HTMLElement, title: string) {
  const name = title.toLowerCase().replace(/[^a-z0-9\-]+/g, "-") + ".pdf";
  const pdf = new jsPDF({ unit: "pt", format: "a4" });

  // temporarily ensure white background
  const canvas = await html2canvas(element, {
    backgroundColor: "#ffffff",
    scale: 2,
    useCORS: true
  });
  const img = canvas.toDataURL("image/png");

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();

  const ratio = Math.min(pageWidth / canvas.width, pageHeight / canvas.height);
  const imgWidth = canvas.width * ratio;
  const imgHeight = canvas.height * ratio;

  const x = (pageWidth - imgWidth) / 2;
  const y = 20;

  pdf.addImage(img, "PNG", x, y, imgWidth, imgHeight);

  pdf.setFont("times", "italic");
  pdf.setFontSize(10);
  pdf.text(`Generated by OAA Lesson Planner — ${new Date().toLocaleDateString()}`, 40, pageHeight - 20);

  pdf.save(name);
}