name: agent-pr
on:
  repository_dispatch:
    types: [agent-run]
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  run-agent:
    if: github.event_name == 'repository_dispatch' || contains(github.event.comment.body, '/agent-run')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Set up Python
        uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install tools
        run: pip install ruff black pytest
      - name: Use plan.json if provided (fallback to example)
        run: |
          if [ ! -f plan.json ]; then
            echo "Using example plan"; cp plan.example.json plan.json
          fi
      - name: Apply planned patch (Hermes)
        run: |
          python .github/agent/apply_patch.py
          ruff .
          black .
      - name: Run tests (if any)
        run: pytest -q || true
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(agent): apply plan (${{ github.sha }})"
          title: "Agent PR: ${{ github.run_id }}"
          body: |
            **Jade plan**: see plan.json
            **Eve check**: simulated in CI
            **Hermes diff**: auto-generated
            **Zeus rule**: label `automerge:safe` after checks pass
          branch: "agent/${{ github.run_id }}"
          labels: "agent, needs-review"
